version: '3.8'

services:
  web:
    build: .
    command: gunicorn bharatfd.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=1

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"